CREATE TABLE notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_email VARCHAR NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP NULL,
  FOREIGN KEY (user_email) REFERENCES users(user_email) ON DELETE CASCADE ON UPDATE CASCADE
);